name: dotnet-build

on:
  pull_request:
    paths:
      - '**.yml'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: build
        run: dotnet build TheIdealShip/TheIdealShip.csproj --configuration Release

      - name: upload TheIdealShip.dll
        uses: actions/upload-artifact@v3
        with:
          name: TheIdealShip
          path: TheIdealShip/bin/Release/net6.0/TheIdealShip.dll