name: Release Action

on:
  workflow_run:
    workflows: [ "dotnet-build" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - uses: dawidd6/action-download-artifact@v2
      with:
        name: TheIdealShip

    - uses: ncipollo/release-action@v1
      with:
        tag: v0.3.4
        bodyFile: "TheIdealShip.dll"