name: Release Action

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.yml'
  workflow_run:
    workflows: [ "dotnet-build" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: TheIdealShip.zip

    - name: uzip
      run: unzip TheIdealShip.zip


    - uses: ncipollo/release-action@v1
      with:
        tag: v0.3.2
        bodyFile: "TheIdealShip.dll"